# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000 # 500000 for 6h_vs_8z

runner: "parallel"
batch_size_run: 8 # batch_size_run=4, buffer_size = 2500, batch_size=64  for 3s5z_vs_3s6z
buffer_size: 5000 
batch_size: 128

t_max: 10050000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "api_mac"
#agent: "api_rnn_densenet"
agent: "api_rnn_densenet_share"
#agent: "api_rnn_residual"
#agent: "api_rnn_residual_share"
api_hyper_dim: 64
#api_hyper_dim: 32
residual_depth: 1
agent_output_type: q

learner: "nq_learner"
mixer: "qmix"
#mixer: "api_qmix_v3"
#mixer: "api_qmix_v8"
#mixer: "api_qmix_v9"

#mixer: "api_qmix_v0"
#mixer: "api_qmix_v0_hyper"
#mixer: "api_qmix"
#mixer: "api_qmix_v3_easy"  # 35.293K
#mixer: "api_qmix_v4_easy"  # 35.293K

#mixer: "api_qmix_v3_instancenorm"  # 35.293K
#mixer: "api_qmix_v3_layernorm"  # 35.293K
#mixer: "api_qmix_v3_w1_origin"  # 35.293K
#mixer: "api_qmix_v3_easier"  # 35.293K
#mixer: "api_qmix_v4_easy"  # 35.293K
#mixer: "api_qmix_v9"  # 35.293K
#mixer: "api_qmix_v10_layernorm"  # 35.293K
#mixer: "api_qmix_v10_groupnorm"  # 35.293K
#mixer: "api_qmix_v10_instancenorm"  # 35.293K
#mixer: "api_qmix_v10_selfatten"  # 34.337K
#mixer: "api_qmix_v11_nohyper_2w"  # 35.293K
#mixer: "api_qmix_v12_nohyper_2w2b"  # 35.293K
#mixer: "api_qmix_v13_nohyper_2b"  # 35.293K
#mixer: "api_qmix_v14_nohyper_1w2b"  # 35.293K
mixing_embed_dim: 32
hypernet_embed: 64
#hypernet_embed: 32
lr: 0.001 # Learning rate for agents
td_lambda: 0.6 # 0.3 for 6h_vs_8z
optimizer: 'adam'
q_lambda: False


#name: "qmix_env=8_adam_td_lambda"
name: "api_qmix_residual"

obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: False # Include the agent's last action (one_hot) in the observation

shared_hyper_input_layer_num: 1
